//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrgWeb.Business.WorkflowEngine.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_ForkNode_m
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MD_ForkNode_m()
        {
            this.MD_ForkNextProcessNode_m = new HashSet<MD_ForkNextProcessNode_m>();
        }
    
        public int ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MD_ForkNextProcessNode_m> MD_ForkNextProcessNode_m { get; set; }
        public virtual MD_ProcessNode_m MD_ProcessNode_m { get; set; }
    }
}
