//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrgWeb.Business.WorkflowEngine.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_JoinPreviousProcessNode_m
    {
        public int ID { get; set; }
        public int JoinNodeID { get; set; }
        public int PreviousProcessNodeID { get; set; }
        public string Title { get; set; }
        public bool IsOptional { get; set; }
        public string OptionalCondition { get; set; }
    
        public virtual MD_ProcessNode_m MD_ProcessNode_m { get; set; }
    }
}
