//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrgWeb.Business.WorkflowEngine.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_Process_m
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MD_Process_m()
        {
            this.MD_ProcessNode_m = new HashSet<MD_ProcessNode_m>();
            this.WF_Process_m = new HashSet<WF_Process_m>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int VoucherKindID { get; set; }
        public int Version { get; set; }
        public bool Active { get; set; }
        public int RegUserID { get; set; }
        public string RegDate { get; set; }
        public Nullable<int> ModifyUserID { get; set; }
        public string ModifyDate { get; set; }
        public int RegCompanyID { get; set; }
    
        public virtual MD_VoucherKind_h MD_VoucherKind_h { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MD_ProcessNode_m> MD_ProcessNode_m { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_Process_m> WF_Process_m { get; set; }
    }
}
