//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrgWeb.Business.WorkflowEngine.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_ProcessNode_m
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MD_ProcessNode_m()
        {
            this.MD_ForkNextProcessNode_m = new HashSet<MD_ForkNextProcessNode_m>();
            this.MD_JoinPreviousProcessNode_m = new HashSet<MD_JoinPreviousProcessNode_m>();
            this.MD_ProcessNode_m1 = new HashSet<MD_ProcessNode_m>();
            this.WF_ProcessExecutionStep_m = new HashSet<WF_ProcessExecutionStep_m>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int ProcessID { get; set; }
        public int NodeKindID { get; set; }
        public Nullable<int> NextProcessNodeID { get; set; }
        public string DesignerLocation { get; set; }
        public string DesignerLinkPath { get; set; }
        public int RegUserID { get; set; }
        public string RegDate { get; set; }
        public Nullable<int> ModifyUserID { get; set; }
        public string ModifyDate { get; set; }
        public int RegCompanyID { get; set; }
    
        public virtual MD_EndEventNode_m MD_EndEventNode_m { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MD_ForkNextProcessNode_m> MD_ForkNextProcessNode_m { get; set; }
        public virtual MD_ForkNode_m MD_ForkNode_m { get; set; }
        public virtual MD_JoinNode_m MD_JoinNode_m { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MD_JoinPreviousProcessNode_m> MD_JoinPreviousProcessNode_m { get; set; }
        public virtual MD_Process_m MD_Process_m { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MD_ProcessNode_m> MD_ProcessNode_m1 { get; set; }
        public virtual MD_ProcessNode_m MD_ProcessNode_m2 { get; set; }
        public virtual MD_ProcessNodeKind_h MD_ProcessNodeKind_h { get; set; }
        public virtual MD_ServiceTaskNode_m MD_ServiceTaskNode_m { get; set; }
        public virtual MD_StartEventNode_m MD_StartEventNode_m { get; set; }
        public virtual MD_TimerNode_m MD_TimerNode_m { get; set; }
        public virtual MD_UserTaskNode_m MD_UserTaskNode_m { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_ProcessExecutionStep_m> WF_ProcessExecutionStep_m { get; set; }
    }
}
