//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrgWeb.Business.WorkflowEngine.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_UserTaskNode_m
    {
        public int ID { get; set; }
        public int RegistrationTypeID { get; set; }
        public bool IsStartTask { get; set; }
    
        public virtual MD_ProcessNode_m MD_ProcessNode_m { get; set; }
        public virtual MD_UserTaskRegistrationType_h MD_UserTaskRegistrationType_h { get; set; }
    }
}
