//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrgWeb.Business.WorkflowEngine.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_VoucherKind_h
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MD_VoucherKind_h()
        {
            this.MD_Process_m = new HashSet<MD_Process_m>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Type { get; set; }
        public string TypeDesc { get; set; }
        public Nullable<int> AttachFormUrlID { get; set; }
        public Nullable<short> IconEnum { get; set; }
        public int WorkSheetPermissionItemID { get; set; }
        public string ServiceAssemblyName { get; set; }
        public string GetMethodName { get; set; }
        public string LatinName { get; set; }
        public bool ClientCenter { get; set; }
        public bool Company { get; set; }
        public bool IsGoverment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MD_Process_m> MD_Process_m { get; set; }
    }
}
