//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrgWeb.Business.WorkflowEngine.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_ProcessExecutionStep_m
    {
        public System.Guid ID { get; set; }
        public int ProcessID { get; set; }
        public int ProcessNodeID { get; set; }
        public System.Guid PathID { get; set; }
        public bool Done { get; set; }
        public long RegisterDateTime { get; set; }
        public Nullable<long> DoneDateTime { get; set; }
        public string PreviousExecutionStepID { get; set; }
        public string Data { get; set; }
        public int RegUserID { get; set; }
        public string RegDate { get; set; }
        public Nullable<int> ModifyUserID { get; set; }
        public string ModifyDate { get; set; }
        public int RegCompanyID { get; set; }
    
        public virtual MD_ProcessNode_m MD_ProcessNode_m { get; set; }
        public virtual WF_Process_m WF_Process_m { get; set; }
    }
}
