//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrgWeb.Business.WorkflowEngine.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_ProcessNodeKind_h
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MD_ProcessNodeKind_h()
        {
            this.MD_ProcessNode_m = new HashSet<MD_ProcessNode_m>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Type { get; set; }
        public string TypeDesc { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MD_ProcessNode_m> MD_ProcessNode_m { get; set; }
    }
}
