//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrgWeb.Business.WorkflowEngine.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_Process_m
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WF_Process_m()
        {
            this.WF_ProcessExecutionStep_m = new HashSet<WF_ProcessExecutionStep_m>();
        }
    
        public int ID { get; set; }
        public int ProcessMetaDataID { get; set; }
        public int VoucherRowID { get; set; }
        public bool Closed { get; set; }
        public int RegUserID { get; set; }
        public string RegDate { get; set; }
        public Nullable<int> ModifyUserID { get; set; }
        public string ModifyDate { get; set; }
        public int RegCompanyID { get; set; }
    
        public virtual MD_Process_m MD_Process_m { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WF_ProcessExecutionStep_m> WF_ProcessExecutionStep_m { get; set; }
    }
}
