//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrgWeb.Business.WorkflowEngine.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkFlowDbContext : DbContext
    {
        public WorkFlowDbContext()
            : base("name=WorkFlowDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MD_EndEventNode_m> MD_EndEventNode_m { get; set; }
        public virtual DbSet<MD_ForkNextProcessNode_m> MD_ForkNextProcessNode_m { get; set; }
        public virtual DbSet<MD_ForkNode_m> MD_ForkNode_m { get; set; }
        public virtual DbSet<MD_JoinNode_m> MD_JoinNode_m { get; set; }
        public virtual DbSet<MD_JoinPreviousProcessNode_m> MD_JoinPreviousProcessNode_m { get; set; }
        public virtual DbSet<MD_Process_m> MD_Process_m { get; set; }
        public virtual DbSet<MD_ProcessNode_m> MD_ProcessNode_m { get; set; }
        public virtual DbSet<MD_ProcessNodeKind_h> MD_ProcessNodeKind_h { get; set; }
        public virtual DbSet<MD_ServiceTaskNode_m> MD_ServiceTaskNode_m { get; set; }
        public virtual DbSet<MD_StartEventNode_m> MD_StartEventNode_m { get; set; }
        public virtual DbSet<MD_TimerNode_m> MD_TimerNode_m { get; set; }
        public virtual DbSet<MD_UserTaskNode_m> MD_UserTaskNode_m { get; set; }
        public virtual DbSet<MD_UserTaskRegistrationType_h> MD_UserTaskRegistrationType_h { get; set; }
        public virtual DbSet<MD_VoucherKind_h> MD_VoucherKind_h { get; set; }
        public virtual DbSet<WF_Process_m> WF_Process_m { get; set; }
        public virtual DbSet<WF_ProcessExecutionStep_m> WF_ProcessExecutionStep_m { get; set; }
    }
}
